apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: topolvm-provisioner
  nfs:
    path: /srv/nfs/kubedata
    server: 127.0.0.1
